CREATE TABLE games (
    game_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    sport TEXT NOT NULL,
    location_name TEXT NOT NULL,
    address TEXT NOT NULL,
    players INT NOT NULL,
    date TEXT NOT NULL
);

CREATE TABLE players(
    player_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    level TEXT NOT NULL,
    comment TEXT,
    game_id INTEGER REFERENCES games(game_id)
);